import type { Food } from './types';

export const DEFAULT_FOODS: Food[] = [
  {
    id: 'df-1',
    name: 'Chicken Breast (Cooked)',
    category: 'protein',
    serving_size: 100,
    serving_unit: 'g',
    calories_per_100g: 165,
    protein_per_100g: 31,
    carbs_per_100g: 0,
    fat_per_100g: 3.6,
    fiber_per_100g: 0,
    is_custom: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'df-2',
    name: 'Boiled Egg',
    category: 'protein',
    serving_size: 50,
    serving_unit: 'piece',
    calories_per_100g: 155,
    protein_per_100g: 12.6,
    carbs_per_100g: 1.1,
    fat_per_100g: 10.6,
    fiber_per_100g: 0,
    is_custom: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'df-3',
    name: 'Paneer (Cottage Cheese)',
    category: 'dairy',
    serving_size: 100,
    serving_unit: 'g',
    calories_per_100g: 296,
    protein_per_100g: 18.3,
    carbs_per_100g: 4.5,
    fat_per_100g: 22,
    fiber_per_100g: 0,
    is_custom: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'df-4',
    name: 'Greek Yogurt (Plain)',
    category: 'dairy',
    serving_size: 100,
    serving_unit: 'g',
    calories_per_100g: 59,
    protein_per_100g: 10,
    carbs_per_100g: 3.6,
    fat_per_100g: 0.4,
    fiber_per_100g: 0,
    is_custom: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'df-5',
    name: 'Cow Milk (Whole)',
    category: 'dairy',
    serving_size: 250,
    serving_unit: 'ml',
    calories_per_100g: 61,
    protein_per_100g: 3.2,
    carbs_per_100g: 4.8,
    fat_per_100g: 3.3,
    fiber_per_100g: 0,
    is_custom: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'df-6',
    name: 'White Rice (Cooked)',
    category: 'grains',
    serving_size: 150,
    serving_unit: 'g',
    calories_per_100g: 130,
    protein_per_100g: 2.7,
    carbs_per_100g: 28.2,
    fat_per_100g: 0.3,
    fiber_per_100g: 0.4,
    is_custom: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'df-7',
    name: 'Brown Rice (Cooked)',
    category: 'grains',
    serving_size: 150,
    serving_unit: 'g',
    calories_per_100g: 111,
    protein_per_100g: 2.6,
    carbs_per_100g: 23,
    fat_per_100g: 0.9,
    fiber_per_100g: 1.8,
    is_custom: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'df-8',
    name: 'Rolled Oats (Raw)',
    category: 'grains',
    serving_size: 50,
    serving_unit: 'g',
    calories_per_100g: 389,
    protein_per_100g: 16.9,
    carbs_per_100g: 66.3,
    fat_per_100g: 6.9,
    fiber_per_100g: 10.6,
    is_custom: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'df-9',
    name: 'Whole Wheat Roti / Chapati',
    category: 'grains',
    serving_size: 40,
    serving_unit: 'piece',
    calories_per_100g: 264,
    protein_per_100g: 9,
    carbs_per_100g: 52,
    fat_per_100g: 3,
    fiber_per_100g: 9,
    is_custom: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'df-10',
    name: 'Yellow Dal (Cooked Tadka)',
    category: 'grains',
    serving_size: 150,
    serving_unit: 'g',
    calories_per_100g: 115,
    protein_per_100g: 6.8,
    carbs_per_100g: 15.2,
    fat_per_100g: 3.1,
    fiber_per_100g: 4.2,
    is_custom: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'df-11',
    name: 'Plain Dosa',
    category: 'grains',
    serving_size: 80,
    serving_unit: 'piece',
    calories_per_100g: 168,
    protein_per_100g: 3.9,
    carbs_per_100g: 29,
    fat_per_100g: 3.7,
    fiber_per_100g: 1.4,
    is_custom: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'df-12',
    name: 'Idli (Steamed)',
    category: 'grains',
    serving_size: 60,
    serving_unit: 'piece',
    calories_per_100g: 132,
    protein_per_100g: 4,
    carbs_per_100g: 28,
    fat_per_100g: 0.5,
    fiber_per_100g: 1.5,
    is_custom: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'df-13',
    name: 'Banana',
    category: 'fruits',
    serving_size: 120,
    serving_unit: 'piece',
    calories_per_100g: 89,
    protein_per_100g: 1.1,
    carbs_per_100g: 22.8,
    fat_per_100g: 0.3,
    fiber_per_100g: 2.6,
    is_custom: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'df-14',
    name: 'Apple (with skin)',
    category: 'fruits',
    serving_size: 150,
    serving_unit: 'piece',
    calories_per_100g: 52,
    protein_per_100g: 0.3,
    carbs_per_100g: 13.8,
    fat_per_100g: 0.2,
    fiber_per_100g: 2.4,
    is_custom: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'df-15',
    name: 'Almonds',
    category: 'nuts',
    serving_size: 30,
    serving_unit: 'g',
    calories_per_100g: 579,
    protein_per_100g: 21.2,
    carbs_per_100g: 21.6,
    fat_per_100g: 49.9,
    fiber_per_100g: 12.5,
    is_custom: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'df-16',
    name: 'Peanut Butter (Smooth)',
    category: 'nuts',
    serving_size: 32,
    serving_unit: 'tbsp',
    calories_per_100g: 588,
    protein_per_100g: 25.1,
    carbs_per_100g: 20,
    fat_per_100g: 50.4,
    fiber_per_100g: 6,
    is_custom: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'df-17',
    name: 'Whey Protein Powder',
    category: 'supplements',
    serving_size: 30,
    serving_unit: 'scoop',
    calories_per_100g: 390,
    protein_per_100g: 80,
    carbs_per_100g: 6,
    fat_per_100g: 4,
    fiber_per_100g: 1,
    is_custom: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'df-18',
    name: 'Salmon (Grilled)',
    category: 'protein',
    serving_size: 150,
    serving_unit: 'g',
    calories_per_100g: 206,
    protein_per_100g: 22.1,
    carbs_per_100g: 0,
    fat_per_100g: 12.3,
    fiber_per_100g: 0,
    is_custom: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'df-19',
    name: 'Broccoli (Steamed)',
    category: 'vegetables',
    serving_size: 100,
    serving_unit: 'g',
    calories_per_100g: 35,
    protein_per_100g: 2.4,
    carbs_per_100g: 7.2,
    fat_per_100g: 0.4,
    fiber_per_100g: 2.6,
    is_custom: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'df-20',
    name: 'Sweet Potato (Baked)',
    category: 'vegetables',
    serving_size: 150,
    serving_unit: 'g',
    calories_per_100g: 90,
    protein_per_100g: 2,
    carbs_per_100g: 20.7,
    fat_per_100g: 0.2,
    fiber_per_100g: 3.3,
    is_custom: false,
    created_at: new Date().toISOString(),
  }
];
